name = "Sacrifice Hotkey"
version = 1
copyright = "Dragun123@2020"
description = "Adds a Hotkey for Sacrifice"
author = "Dragun123"
uid = "HOTKEY-SACR-498f-8c44-a05d4b8985x2"
selectable = true
icon = "/mods/Sacrifice/Sacrifice.png"
enabled = true
exclusive = false
ui_only = true
requires = {}
conflicts = {}
before = {}
after = {}